# YML file for setting up a virtual environment including packages used for accessing APIs and basic geometry operations.

name: geoapis
channels:
  - conda-forge
dependencies:
  - pip
  - geopandas
  - requests
  - boto3
  - python-dotenv
  - pytest
  - tqdm
